# Generated by Django 4.1 on 2022-11-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
